### ISSUE TITLE
WorldEdit doesn't work with Better Badlands

### ISSUE THREAD

**Issue by thepwrtank18** [teamauroramods/BetterBadlands-Forge#21]
When I have Better Badlands alongside WorldEdit, commands on WorldEdit do not show up, and trying to type them in will say that the command doesn't exist. There is no error message in the logs.

**Comment by TrueGkoliver** [comment]
Uhh... could you give your logs? I want to take a closer look at them.

**Comment by thepwrtank18** [comment]
[without-badlands.log](https://github.com/teamauroramods/BetterBadlands/files/5599553/without-badlands.log)
[with-badlands.log](https://github.com/teamauroramods/BetterBadlands/files/5599554/with-badlands.log)
@TrueGkoliver

**Comment by TrueGkoliver** [comment]
Hm. I... don't know. Perhaps @Epic312 can try and see what is happening here?

**Comment by ex0planetary** [comment]
How are you running BB and WorldEdit in the same instance? Looking on their CF page I can't seem to find a version for Forge 1.16.1 (which I need to debug this). If there's no official way to download it and the version you're using is unofficial it might be best to wait til 1.16.4 and see if that helps.

**Comment by thepwrtank18** [comment]
> How are you running BB and WorldEdit in the same instance? Looking on their CF page I can't seem to find a version for Forge 1.16.1 (which I need to debug this). If there's no official way to download it and the version you're using is unofficial it might be best to wait til 1.16.4 and see if that helps.

Apparently they deleted the build for 1.16.1 for some reason. The only way I could get it was through 9minecraft.net (ew).
@Epic312

**Comment by thepwrtank18** [comment]
I did have the version on CF before I deleted it by accident, and it had the same issue.

**Comment by ex0planetary** [comment]
If it's 9minecraft good chance it's a modified or bootleg version of the mod. As such we don't support issues with them. So I'm gonna close this until 1.16.4 - once we're ported I'll see if the bug still persists and if it does I'll reopen so we can patch it.

**Comment by thepwrtank18** [comment]
With a VirusTotal scan and some googling, I can confirm that it is the original, unmodified file, as the original file name was `worldedit_forge_mc1.16.1_7.2.0_beta_03.jar`, which is exactly what the file name was before it was removed.

https://www.virustotal.com/gui/file/cff8611443fb70ebcb38e3e50a403341010c7dd2984809ce1433ef54f63b0d0d/detection

**Comment by ex0planetary** [comment]
ah yes because the rename button totally isn't a thing that exists

**Comment by thepwrtank18** [comment]
Don't look at the detections, but look at above it, and you will see what I mean.

Here is the file (extract it for the jar) just in case:
[WorldEdit-1.16.1.zip](https://github.com/teamauroramods/BetterBadlands/files/5599657/WorldEdit-1.16.1.zip)

**Comment by thepwrtank18** [comment]
checksums match, and those can't be renamed

**Comment by ex0planetary** [comment]
Installed the file and I can't reproduce the issue. I'm able to use all commands perfectly fine. Try a restart or something I guess, or a reinstall of the mods, idk
