### ISSUE TITLE
(suggestion) Acacia Trees should generate on Wooded Badlands

### ISSUE THREAD

**Issue by Brun333rp** [teamauroramods/BetterBadlands-Forge#29]
It makes sense, because acacias seem to be adapted to dry climates, and it would bring some wood variety to this biome.

**Comment by ex0planetary** [comment]
I get where you're coming from but they don't really fit with the aesthethic.

**Comment by Brun333rp** [comment]
well, if you think so ... I personally think that they fit very well, and they would look great in Wooded Badlands biome

**Comment by Brun333rp** [comment]
maybe the problem here is the tree's shape. so perhaps if they had a different shape from the savanna acacias they would fit better

**Comment by ex0planetary** [comment]
nah, I think the badlands have enough wood sets already. 2 is plenty for one biome.
